configuration:
  projectName: Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: configprops
server.port: 8888
spring.cloud.config.server.git.uri: https://github.com/cloud-native-java/config-server-configuration-repository